services:
 postgres:
  image: postgres:17-alpine
  env_file:
   - .env
  environment:
   POSTGRES_DB: ${DB_NAME}
   POSTGRES_USER: ${DB_USER}
   POSTGRES_PASSWORD: ${DB_PASSWORD}
  volumes:
   - ./postgres-data:/var/lib/postgresql/data
  ports:
   - "${DB_PORT}:5432"
  restart:
   unless-stopped
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
   interval: 5s
   timeout: 5s
   retries: 5
  logging:
   driver: "json-file"
   options:
    max-size: "10m"
    max-file: "5"
    compress: "true"
  networks:
   - app_network

 pgadmin:
  image: dpage/pgadmin4
  container_name: pgadmin
  env_file:
   - .env
  environment:
   PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
   PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  volumes:
   - ./pgadmin-data:/var/lib/pgadmin
  ports:
   - "${PGADMIN_PORT}:80"
  restart: unless-stopped
  depends_on:
   postgres:
    condition: service_healthy
  logging:
   driver: "json-file"
   options:
    max-size: "10m"
    max-file: "5"
    compress: "true"
  networks:
   - app_network

networks:
 app_network:
  name: app_network